# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from hermes.protos import broker_pb2 as hermes_dot_protos_dot_broker__pb2


class BrokerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamCommands = channel.unary_stream(
                '/hermes.BrokerService/StreamCommands',
                request_serializer=hermes_dot_protos_dot_broker__pb2.Empty.SerializeToString,
                response_deserializer=hermes_dot_protos_dot_broker__pb2.SystemCommand.FromString,
                )
        self.SubmitOrder = channel.unary_unary(
                '/hermes.BrokerService/SubmitOrder',
                request_serializer=hermes_dot_protos_dot_broker__pb2.MultiLegOrder.SerializeToString,
                response_deserializer=hermes_dot_protos_dot_broker__pb2.ExecutionReport.FromString,
                )
        self.QueryPositions = channel.unary_stream(
                '/hermes.BrokerService/QueryPositions',
                request_serializer=hermes_dot_protos_dot_broker__pb2.Empty.SerializeToString,
                response_deserializer=hermes_dot_protos_dot_broker__pb2.BrokerPosition.FromString,
                )
        self.StreamQuotes = channel.unary_stream(
                '/hermes.BrokerService/StreamQuotes',
                request_serializer=hermes_dot_protos_dot_broker__pb2.Empty.SerializeToString,
                response_deserializer=hermes_dot_protos_dot_broker__pb2.MarketQuote.FromString,
                )
        self.GetAccountBalances = channel.unary_unary(
                '/hermes.BrokerService/GetAccountBalances',
                request_serializer=hermes_dot_protos_dot_broker__pb2.Empty.SerializeToString,
                response_deserializer=hermes_dot_protos_dot_broker__pb2.BalancesResponse.FromString,
                )
        self.GetOrders = channel.unary_unary(
                '/hermes.BrokerService/GetOrders',
                request_serializer=hermes_dot_protos_dot_broker__pb2.Empty.SerializeToString,
                response_deserializer=hermes_dot_protos_dot_broker__pb2.JSONResponse.FromString,
                )
        self.CancelOrder = channel.unary_unary(
                '/hermes.BrokerService/CancelOrder',
                request_serializer=hermes_dot_protos_dot_broker__pb2.CancelOrderRequest.SerializeToString,
                response_deserializer=hermes_dot_protos_dot_broker__pb2.JSONResponse.FromString,
                )
        self.GetOptionExpirations = channel.unary_unary(
                '/hermes.BrokerService/GetOptionExpirations',
                request_serializer=hermes_dot_protos_dot_broker__pb2.ExpirationsRequest.SerializeToString,
                response_deserializer=hermes_dot_protos_dot_broker__pb2.ExpirationsResponse.FromString,
                )
        self.GetOptionChains = channel.unary_unary(
                '/hermes.BrokerService/GetOptionChains',
                request_serializer=hermes_dot_protos_dot_broker__pb2.OptionChainsRequest.SerializeToString,
                response_deserializer=hermes_dot_protos_dot_broker__pb2.JSONResponse.FromString,
                )
        self.GetQuote = channel.unary_unary(
                '/hermes.BrokerService/GetQuote',
                request_serializer=hermes_dot_protos_dot_broker__pb2.QuoteRequest.SerializeToString,
                response_deserializer=hermes_dot_protos_dot_broker__pb2.JSONResponse.FromString,
                )
        self.GetDelta = channel.unary_unary(
                '/hermes.BrokerService/GetDelta',
                request_serializer=hermes_dot_protos_dot_broker__pb2.DeltaRequest.SerializeToString,
                response_deserializer=hermes_dot_protos_dot_broker__pb2.DeltaResponse.FromString,
                )
        self.GetHistory = channel.unary_unary(
                '/hermes.BrokerService/GetHistory',
                request_serializer=hermes_dot_protos_dot_broker__pb2.HistoryRequest.SerializeToString,
                response_deserializer=hermes_dot_protos_dot_broker__pb2.JSONResponse.FromString,
                )
        self.AnalyzeSymbol = channel.unary_unary(
                '/hermes.BrokerService/AnalyzeSymbol',
                request_serializer=hermes_dot_protos_dot_broker__pb2.AnalyzeRequest.SerializeToString,
                response_deserializer=hermes_dot_protos_dot_broker__pb2.JSONResponse.FromString,
                )
        self.RollToNextMonth = channel.unary_unary(
                '/hermes.BrokerService/RollToNextMonth',
                request_serializer=hermes_dot_protos_dot_broker__pb2.RollRequest.SerializeToString,
                response_deserializer=hermes_dot_protos_dot_broker__pb2.RollResponse.FromString,
                )


class BrokerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamCommands(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryPositions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamQuotes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccountBalances(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrders(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOptionExpirations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOptionChains(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetQuote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDelta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeSymbol(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RollToNextMonth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BrokerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamCommands': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamCommands,
                    request_deserializer=hermes_dot_protos_dot_broker__pb2.Empty.FromString,
                    response_serializer=hermes_dot_protos_dot_broker__pb2.SystemCommand.SerializeToString,
            ),
            'SubmitOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitOrder,
                    request_deserializer=hermes_dot_protos_dot_broker__pb2.MultiLegOrder.FromString,
                    response_serializer=hermes_dot_protos_dot_broker__pb2.ExecutionReport.SerializeToString,
            ),
            'QueryPositions': grpc.unary_stream_rpc_method_handler(
                    servicer.QueryPositions,
                    request_deserializer=hermes_dot_protos_dot_broker__pb2.Empty.FromString,
                    response_serializer=hermes_dot_protos_dot_broker__pb2.BrokerPosition.SerializeToString,
            ),
            'StreamQuotes': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamQuotes,
                    request_deserializer=hermes_dot_protos_dot_broker__pb2.Empty.FromString,
                    response_serializer=hermes_dot_protos_dot_broker__pb2.MarketQuote.SerializeToString,
            ),
            'GetAccountBalances': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccountBalances,
                    request_deserializer=hermes_dot_protos_dot_broker__pb2.Empty.FromString,
                    response_serializer=hermes_dot_protos_dot_broker__pb2.BalancesResponse.SerializeToString,
            ),
            'GetOrders': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrders,
                    request_deserializer=hermes_dot_protos_dot_broker__pb2.Empty.FromString,
                    response_serializer=hermes_dot_protos_dot_broker__pb2.JSONResponse.SerializeToString,
            ),
            'CancelOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelOrder,
                    request_deserializer=hermes_dot_protos_dot_broker__pb2.CancelOrderRequest.FromString,
                    response_serializer=hermes_dot_protos_dot_broker__pb2.JSONResponse.SerializeToString,
            ),
            'GetOptionExpirations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOptionExpirations,
                    request_deserializer=hermes_dot_protos_dot_broker__pb2.ExpirationsRequest.FromString,
                    response_serializer=hermes_dot_protos_dot_broker__pb2.ExpirationsResponse.SerializeToString,
            ),
            'GetOptionChains': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOptionChains,
                    request_deserializer=hermes_dot_protos_dot_broker__pb2.OptionChainsRequest.FromString,
                    response_serializer=hermes_dot_protos_dot_broker__pb2.JSONResponse.SerializeToString,
            ),
            'GetQuote': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQuote,
                    request_deserializer=hermes_dot_protos_dot_broker__pb2.QuoteRequest.FromString,
                    response_serializer=hermes_dot_protos_dot_broker__pb2.JSONResponse.SerializeToString,
            ),
            'GetDelta': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDelta,
                    request_deserializer=hermes_dot_protos_dot_broker__pb2.DeltaRequest.FromString,
                    response_serializer=hermes_dot_protos_dot_broker__pb2.DeltaResponse.SerializeToString,
            ),
            'GetHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHistory,
                    request_deserializer=hermes_dot_protos_dot_broker__pb2.HistoryRequest.FromString,
                    response_serializer=hermes_dot_protos_dot_broker__pb2.JSONResponse.SerializeToString,
            ),
            'AnalyzeSymbol': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeSymbol,
                    request_deserializer=hermes_dot_protos_dot_broker__pb2.AnalyzeRequest.FromString,
                    response_serializer=hermes_dot_protos_dot_broker__pb2.JSONResponse.SerializeToString,
            ),
            'RollToNextMonth': grpc.unary_unary_rpc_method_handler(
                    servicer.RollToNextMonth,
                    request_deserializer=hermes_dot_protos_dot_broker__pb2.RollRequest.FromString,
                    response_serializer=hermes_dot_protos_dot_broker__pb2.RollResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hermes.BrokerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BrokerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamCommands(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/hermes.BrokerService/StreamCommands',
            hermes_dot_protos_dot_broker__pb2.Empty.SerializeToString,
            hermes_dot_protos_dot_broker__pb2.SystemCommand.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SubmitOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hermes.BrokerService/SubmitOrder',
            hermes_dot_protos_dot_broker__pb2.MultiLegOrder.SerializeToString,
            hermes_dot_protos_dot_broker__pb2.ExecutionReport.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def QueryPositions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/hermes.BrokerService/QueryPositions',
            hermes_dot_protos_dot_broker__pb2.Empty.SerializeToString,
            hermes_dot_protos_dot_broker__pb2.BrokerPosition.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamQuotes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/hermes.BrokerService/StreamQuotes',
            hermes_dot_protos_dot_broker__pb2.Empty.SerializeToString,
            hermes_dot_protos_dot_broker__pb2.MarketQuote.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAccountBalances(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hermes.BrokerService/GetAccountBalances',
            hermes_dot_protos_dot_broker__pb2.Empty.SerializeToString,
            hermes_dot_protos_dot_broker__pb2.BalancesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hermes.BrokerService/GetOrders',
            hermes_dot_protos_dot_broker__pb2.Empty.SerializeToString,
            hermes_dot_protos_dot_broker__pb2.JSONResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CancelOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hermes.BrokerService/CancelOrder',
            hermes_dot_protos_dot_broker__pb2.CancelOrderRequest.SerializeToString,
            hermes_dot_protos_dot_broker__pb2.JSONResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetOptionExpirations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hermes.BrokerService/GetOptionExpirations',
            hermes_dot_protos_dot_broker__pb2.ExpirationsRequest.SerializeToString,
            hermes_dot_protos_dot_broker__pb2.ExpirationsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetOptionChains(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hermes.BrokerService/GetOptionChains',
            hermes_dot_protos_dot_broker__pb2.OptionChainsRequest.SerializeToString,
            hermes_dot_protos_dot_broker__pb2.JSONResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetQuote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hermes.BrokerService/GetQuote',
            hermes_dot_protos_dot_broker__pb2.QuoteRequest.SerializeToString,
            hermes_dot_protos_dot_broker__pb2.JSONResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDelta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hermes.BrokerService/GetDelta',
            hermes_dot_protos_dot_broker__pb2.DeltaRequest.SerializeToString,
            hermes_dot_protos_dot_broker__pb2.DeltaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hermes.BrokerService/GetHistory',
            hermes_dot_protos_dot_broker__pb2.HistoryRequest.SerializeToString,
            hermes_dot_protos_dot_broker__pb2.JSONResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AnalyzeSymbol(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hermes.BrokerService/AnalyzeSymbol',
            hermes_dot_protos_dot_broker__pb2.AnalyzeRequest.SerializeToString,
            hermes_dot_protos_dot_broker__pb2.JSONResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RollToNextMonth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hermes.BrokerService/RollToNextMonth',
            hermes_dot_protos_dot_broker__pb2.RollRequest.SerializeToString,
            hermes_dot_protos_dot_broker__pb2.RollResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
