"""Static interfaces (protocols) to decouple the trading engine from Tradier and TimescaleDB."""
from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

@runtime_checkable
class IBroker(Protocol):
    """Normalized broker interface for both live execution and backtests."""
    @property
    def current_date(self) -> Any: ...
    @property
    def dry_run(self) -> bool: ...

    async def get_account_balances(self) -> dict[str, Any]: ...
    async def get_positions(self) -> list[dict[str, Any]]: ...
    async def get_orders(self) -> list[dict[str, Any]]: ...
    async def get_option_expirations(self, symbol: str) -> list[str]: ...
    async def get_option_chains(self, symbol: str, expiry: str) -> list[dict[str, Any]]: ...
    async def get_quote(self, symbols: str) -> list[dict[str, Any]]: ...
    async def place_order_from_action(self, action: Any) -> dict[str, Any]: ...
    async def roll_to_next_month(self, option_symbol: str) -> str: ...
    async def analyze_symbol(self, symbol: str, period: str = "6m") -> dict[str, Any]: ...


@runtime_checkable
class IDatabase(Protocol):
    """Persistence repository interface for state logging, telemetry, and tracking."""
    async def write_log(self, strategy_id: str, msg: str, level: str = "INFO") -> None: ...
    async def upsert_positions(self, positions: list[dict[str, Any]], active_order_legs: set[str]) -> None: ...
    async def tracked_option_symbols(self) -> set[str]: ...
    async def flag_orphans(self, orphans: set[str]) -> None: ...
    async def open_trades(self, strategy_id: str) -> list[dict[str, Any]]: ...
    async def all_open_trades(self) -> list[dict[str, Any]]: ...
    async def open_legs(self, strategy_id: str, symbol: str) -> list[dict[str, Any]]: ...
    async def latest_prediction(self, symbol: str) -> dict[str, Any] | None: ...
    async def count_open_contracts(self, strategy_id: str, symbol: str, side: str, expiry: str) -> int: ...
    async def count_pending_orders(self, strategy_id: str, symbol: str, side: str, expiry: str) -> int: ...
    async def equity_position(self, symbol: str) -> int: ...
    async def has_pending_approval(self, strategy_id: str, symbol: str, side: str, expiry: str) -> bool: ...
    async def get_setting(self, key: str, default: str | None = None) -> str | None: ...
    async def set_setting(self, key: str, value: str) -> None: ...
    async def write_ai_decision(self, strategy_id: str, symbol: str, autonomy: str, decision: dict[str, Any]) -> None: ...
    async def record_pending_order(self, action: Any) -> None: ...
    async def record_order_response(self, action: Any, response: dict[str, Any]) -> None: ...
    async def close_trade_from_action(self, action: Any, response: dict[str, Any]) -> None: ...
    async def queue_for_approval(self, action_dict: dict[str, Any], action_type: str = "entry") -> None: ...
    async def recent_logs(self, limit: int = 200) -> str: ...
